/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2022 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
#include "main.h"
#include "usart.h"
#include "gpio.h"
#include "usb/usb.h"
#include "switch/switch.h"
#include "switch/switch_desc.h"
#include "debug_uart.h"

#include "tusb_config.h"
#include "tusb.h"

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
#warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

void SystemClock_Config(void);





// ---- UART Command Protocol ----
#define CMD_START 0xAA

// UART RX state machine — runs entirely in ISR for zero-latency re-arm
typedef enum { RX_WAIT_START, RX_WAIT_CMD, RX_WAIT_LF } rx_state_t;
static volatile rx_state_t rx_state = RX_WAIT_START;
static uint8_t    rx_byte;

// Command received from ISR, processed in main loop
static volatile uint8_t pending_cmd = 0;  // 'R', 'P', or 0 (none)

// Reset macro state: buttons for 500ms, then idle for 1500ms, then resume A
static volatile bool     reset_active = false;
static volatile uint32_t reset_start_ms = 0;
#define RESET_ABXY_MS   500   // hold all buttons (title screen reset)
static volatile uint32_t reset_pause_ms = 2000;  // randomised 2000-4000ms each reset

// Lightweight xorshift32 PRNG for randomising A-press intervals
static uint32_t rng_state = 1;
static uint32_t xorshift32(void)
{
    uint32_t x = rng_state;
    x ^= x << 13;
    x ^= x >> 17;
    x ^= x << 5;
    rng_state = x;
    return x;
}
// Returns a random value in [min, max] inclusive
static uint32_t rand_range(uint32_t min, uint32_t max)
{
    return min + (xorshift32() % (max - min + 1));
}

static void send_ack(void)
{
    uint8_t ack[] = { CMD_START, 'K', '\n' };
    HAL_UART_Transmit(&huart1, ack, 3, 10);
}

// Called from UART RX complete ISR — parse + re-arm immediately
void HAL_UART_RxCpltCallback(UART_HandleTypeDef *huart)
{
    if(huart->Instance != USART1) return;

    switch(rx_state)
    {
    case RX_WAIT_START:
        if(rx_byte == CMD_START)
            rx_state = RX_WAIT_CMD;
        break;

    case RX_WAIT_CMD:
        if(rx_byte == 'R' || rx_byte == 'P')
            pending_cmd = rx_byte;
        rx_state = RX_WAIT_LF;
        break;

    case RX_WAIT_LF:
        rx_state = RX_WAIT_START;
        break;
    }

    // Re-arm immediately — no gap between bytes
    HAL_UART_Receive_IT(&huart1, &rx_byte, 1);
}

// Start listening for one byte (non-blocking, interrupt-driven)
static void uart_listen(void)
{
    HAL_UART_Receive_IT(&huart1, &rx_byte, 1);
}

// Process pending commands in main loop (debug prints + ACK)
static void uart_poll(void)
{
    uint8_t cmd = pending_cmd;
    if(cmd == 0) return;
    pending_cmd = 0;

    switch(cmd)
    {
    case 'R':
        reset_active = true;
        reset_start_ms = HAL_GetTick();
        reset_pause_ms = rand_range(2000, 4000);
        send_ack();
        debug_println("[CMD] RESET");
        break;
    case 'P':
        send_ack();
        debug_println("[CMD] PING");
        break;
    }
}




//static void hw_setup()
//{
//    // Enable clocks to the GPIO subsystems (PB for ADC), turn on AFIO clocking to disable SWD/JTAG
//    RCC->APB2ENR |= RCC_APB2ENR_IOPAEN | RCC_APB2ENR_IOPBEN | RCC_APB2ENR_IOPCEN | RCC_APB2ENR_AFIOEN;
//    // turn off SWJ/JTAG
//    //AFIO->MAPR = AFIO_MAPR_SWJ_CFG_DISABLE;
//    // turn off USB pullup
//    GPIOA->ODR = (1 << 13);
//    // Set led (PC13) as opendrain output
//    GPIOC->CRH = CRH(13, CNF_ODOUTPUT | MODE_SLOW);
//    // Set USB pullup (PA13) as opendrain output
//    GPIOA->CRH = CRH(13, CNF_ODOUTPUT | MODE_SLOW);
//}

//static void iwdg_setup()
//{
//    uint32_t tmout = 16000000;
//    /* Enable the peripheral clock RTC */
//    /* (1) Enable the LSI (40kHz) */
//    /* (2) Wait while it is not ready */
//    RCC->CSR |= RCC_CSR_LSION; /* (1) */
//    while((RCC->CSR & RCC_CSR_LSIRDY) != RCC_CSR_LSIRDY)
//    {
//        if(--tmout == 0) break;   /* (2) */
//    }
//    /* Configure IWDG */
//    /* (1) Activate IWDG (not needed if done in option bytes) */
//    /* (2) Enable write access to IWDG registers */
//    /* (3) Set prescaler by 64 (1.6ms for each tick) */
//    /* (4) Set reload value to have a rollover each 2s */
//    /* (5) Check if flags are reset */
//    /* (6) Refresh counter */
//    IWDG->KR = IWDG_START; /* (1) */
//    IWDG->KR = IWDG_WRITE_ACCESS; /* (2) */
//    IWDG->PR = IWDG_PR_PR_1; /* (3) */
//    IWDG->RLR = 1250; /* (4) */
//    tmout = 16000000;
//    while(IWDG->SR)
//    {
//        if(--tmout == 0) break;   /* (5) */
//    }
//    IWDG->KR = IWDG_REFRESH; /* (6) */
//}

///*
// * buf[0]: 1 - report ID
// * buf[1]: bit2 - middle button, bit1 - right, bit0 - left
// * buf[2]: move X
// * buf[3]: move Y
// * buf[4]: wheel
// */
//static void move_mouse(int8_t x, int8_t y)
//{
//    int8_t buf[5] = {1, 0, 0, 0, 0};
//    buf[2] = x;
//    buf[3] = y;
//    USB_send((uint8_t *)buf, 5);
//}
//
///*
// * Keyboard buffer:
// * buf[1]: MOD
// * buf[2]: reserved
// * buf[3]..buf[8] - keycodes 1..6
// */
//static void send_word(const char *wrd)
//{
//    char last = 0;
//    do
//    {
//        // release key before pressing it again
//        if(last == *wrd) USB_send(release_key(), USB_KEYBOARD_REPORT_SIZE);
//        last = *wrd;
//        USB_send(press_key(last), USB_KEYBOARD_REPORT_SIZE);
//        IWDG->KR = IWDG_REFRESH;
//        USB_send(release_key(), USB_KEYBOARD_REPORT_SIZE);
//        IWDG->KR = IWDG_REFRESH;
//    }
//    while(*(++wrd));
//    USB_send(release_key(), USB_KEYBOARD_REPORT_SIZE);
//}

#if 0
static char *parse_cmd(char *buf)
{
    if(buf[1] != '\n' && buf[1] != '\r')
        return buf;

    switch(*buf)
    {
//    case 'p':
//        pin_toggle(USBPU_port, USBPU_pin);
//        SEND("USB pullup is ");
//        if(pin_read(USBPU_port, USBPU_pin)) SEND("off");
//        else SEND("on");
//        newline();
//        break;
//    case 'C':
//        SEND("USB ");
//        if(!usbON) SEND("dis");
//        SEND("connected\r\n");
//        break;
//    case 'k':
//    	send_word("k");
//    	SEND("Write one letter\r\n");
//		break;
//    case 'K':
//        send_word("Hello, weird and cruel world!\n\n");
//        SEND("Write hello\r\n");
//        break;
//    case 'M':
//        move_mouse(100, 10);
//        move_mouse(0, 0);
//        SEND("Move mouse\r\n");
//        break;
//    case 'm':
//        move_mouse(-100, -10);
//        move_mouse(0, 0);
//        SEND("Move mouse\r\n");
//        break;
    case 'R':
        debug_print("Soft reset\r\n");
        NVIC_SystemReset();
        break;
    case 'W':
        debug_print("Wait for reboot\r\n");
        while(1)
            __NOP(); ;
        break;
    default: // help
        return
            "'p' - toggle USB pullup\r\n"
            "'C' - test if USB is configured\r\n"
            "'K' - emulate keyboard\r\n"
            "'M' - move mouse\r\n"
            "'R' - software reset\r\n"
            "'W' - test watchdog\r\n"
            ;
        break;
    }
    return NULL;
}
#endif

int main(void)
{
    uint32_t lastT = 0;
    tusb_rhport_init_t dev_init =
    {
        .role = TUSB_ROLE_DEVICE,
        .speed = TUSB_SPEED_FULL
    };

    HAL_Init();

    SystemClock_Config();

//    StartHSE();
//    hw_setup();
//    usart_setup();
    MX_GPIO_Init();
    MX_USB_PCD_Init();
    MX_USART1_UART_Init();

    debug_init(&huart1);
    debug_println("=== Auto Switch Pro boot ===");

//    SEND("Hello! I'm ready.\n");
//
//    if(RCC->CSR & RCC_CSR_IWDGRSTF)  // watchdog reset occured
//        SEND("WDGRESET=1\n");
//
//    if(RCC->CSR & RCC_CSR_SFTRSTF)  // software reset occured
//        SEND("SOFTRESET=1\n");
//
//    RCC->CSR |= RCC_CSR_RMVF; // remove reset flags


    // LED on at boot (PB2, active-low)
    HAL_GPIO_WritePin(LED_GPIO_Port, LED_Pin, GPIO_PIN_RESET);


    // Initialise TinyUSB (resets USB peripheral, opens EP0, enables D+ pull-up + NVIC)
    tusb_init(BOARD_TUD_RHPORT, &dev_init);
    tud_sof_cb_enable(true);

    // Soft-reconnect: pull D+ low, wait, then re-assert.
    // The STM32H5 boots so fast that D+ goes high almost instantly after VBUS.
    // Strict USB hosts (like the Switch dock) need to see a clean transition.
    tud_disconnect();
    HAL_Delay(2000);
    tud_connect();

//    USBPU_OFF();
//    USB_setup();
//    iwdg_setup();
//    USBPU_ON();

    debug_println("USB connected, waiting for host...");

    // Enable USART1 interrupt (CubeMX didn't enable it in NVIC)
    HAL_NVIC_SetPriority(USART1_IRQn, 1, 0);
    HAL_NVIC_EnableIRQ(USART1_IRQn);

    // Start non-blocking UART receive for command protocol
    uart_listen();

    while(1)
    {
//        IWDG->KR = IWDG_REFRESH; // refresh watchdog

        uint32_t t = HAL_GetTick();

        if(lastT > t || t - lastT > 499)
        {
//            LED_blink();
            HAL_GPIO_TogglePin(LED_GPIO_Port, LED_Pin);
            lastT = t;
//            transmit_tbuf(); // non-blocking transmission of data from UART buffer every 0.5s
        }

        tud_task();

        // Service any queued protocol responses (handshake, subcommand replies)
        switch_pro_send_queued();

        uart_poll();

//        int r = 0;
//        char *txt, *ans;
//
//        if(usartrx())  // usart1 received data, store in in buffer
//        {
//        	SEND("Fuck?\r\n");
//            r = usart_getline(&txt);
//            if(r)
//            {
//                txt[r] = 0;
//                SEND("\r\n\r\n\r\n");
//                SEND(txt);
//                SEND("\r\n\r\n\r\n");
//                ans = parse_cmd(txt);
//                if(ans)
//                {
//                    usart_send(ans);
//                    transmit_tbuf();
//                }
//            }
//        }
    }

    return 0;
}

/**
  * @brief  System Clock Configuration
  *         The system Clock is configured as follow :
  *            System Clock source            = PLL (HSE)
  *            SYSCLK(Hz)                     = 72000000
  *            HCLK(Hz)                       = 72000000
  *            AHB Prescaler                  = 1
  *            APB1 Prescaler                 = 2
  *            APB2 Prescaler                 = 1
  *            PLLMUL                         = 16
  *            Flash Latency(WS)              = 2
  * @param  None
  * @retval None
  */
void SystemClock_Config(void)
{
    RCC_ClkInitTypeDef clkinitstruct = {0};
    RCC_OscInitTypeDef oscinitstruct = {0};
    RCC_PeriphCLKInitTypeDef rccperiphclkinit = {0};

    /* Enable HSE Oscillator and activate PLL with HSE as source */
    oscinitstruct.OscillatorType  = RCC_OSCILLATORTYPE_HSE;
    oscinitstruct.HSEState        = RCC_HSE_ON;
    oscinitstruct.HSEPredivValue  = RCC_HSE_PREDIV_DIV2;
    oscinitstruct.PLL.PLLMUL      = RCC_PLL_MUL9;
    oscinitstruct.PLL.PLLState    = RCC_PLL_ON;
    oscinitstruct.PLL.PLLSource   = RCC_PLLSOURCE_HSE;

    if (HAL_RCC_OscConfig(&oscinitstruct)!= HAL_OK)
    {
        while(1) { ; }
    }

    /* USB clock selection */
    rccperiphclkinit.PeriphClockSelection = RCC_PERIPHCLK_USB;
    rccperiphclkinit.UsbClockSelection = RCC_USBCLKSOURCE_PLL_DIV1_5;
    if(HAL_RCCEx_PeriphCLKConfig(&rccperiphclkinit) != HAL_OK)
    {
        while(1) { ; }
    }

    /* Select PLL as system clock source and configure the HCLK, PCLK1 and PCLK2 clocks dividers */
    clkinitstruct.ClockType = (RCC_CLOCKTYPE_SYSCLK | RCC_CLOCKTYPE_HCLK | RCC_CLOCKTYPE_PCLK1 | RCC_CLOCKTYPE_PCLK2);
    clkinitstruct.SYSCLKSource = RCC_SYSCLKSOURCE_HSI;
    clkinitstruct.AHBCLKDivider = RCC_SYSCLK_DIV1;
    clkinitstruct.APB2CLKDivider = RCC_HCLK_DIV1;
    clkinitstruct.APB1CLKDivider = RCC_HCLK_DIV1;
    if (HAL_RCC_ClockConfig(&clkinitstruct, FLASH_LATENCY_0)!= HAL_OK)
    {
        /* Initialisation Error */
        while(1);
    }

    /* Select PLL as system clock source and configure the HCLK, PCLK1 and PCLK2 clocks dividers */
    clkinitstruct.ClockType = (RCC_CLOCKTYPE_SYSCLK | RCC_CLOCKTYPE_HCLK | RCC_CLOCKTYPE_PCLK1 | RCC_CLOCKTYPE_PCLK2);
    clkinitstruct.SYSCLKSource = RCC_SYSCLKSOURCE_PLLCLK;
    clkinitstruct.AHBCLKDivider = RCC_SYSCLK_DIV1;
    clkinitstruct.APB1CLKDivider = RCC_HCLK_DIV2;
    clkinitstruct.APB2CLKDivider = RCC_HCLK_DIV1;
    HAL_RCC_ClockConfig(&clkinitstruct, FLASH_LATENCY_2);
}

void Error_Handler(void)
{
    __disable_irq();
    while(1)
    {}
}
