/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2022 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
#include "main.h"
#include "usart.h"
#include "gpio.h"
#include "usb/usb.h"
#include "usb/usb_extra.h"
#include "switch/switch.h"
#include "switch/switch_desc.h"
#include "debug_uart.h"

#include "tusb_config.h"
#include "tusb.h"

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
#warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

void SystemClock_Config(void);

#define MODE_SLOW       2  // 2MHz
#define CNF_ODOUTPUT    (1 << 2)
#define CRH(pin, cnfmode)  ((cnfmode) << ((pin-8)*4))

__attribute__((always_inline)) static inline void sysreset(void)
{
    /* Reset the RCC clock configuration to the default reset state(for debug purpose) */
    /* Set HSION bit */
    RCC->CR |= (uint32_t)0x00000001;
    /* Reset SW, HPRE, PPRE1, PPRE2, ADCPRE and MCO bits */
    RCC->CFGR &= (uint32_t)0xF8FF0000;
    /* Reset HSEON, CSSON and PLLON bits */
    RCC->CR &= (uint32_t)0xFEF6FFFF;
    /* Reset HSEBYP bit */
    RCC->CR &= (uint32_t)0xFFFBFFFF;
    /* Reset PLLSRC, PLLXTPRE, PLLMUL and USBPRE/OTGFSPRE bits */
    RCC->CFGR &= (uint32_t)0xFF80FFFF;
    /* Disable all interrupts and clear pending bits  */
    RCC->CIR = 0x009F0000;

    SCB->VTOR = FLASH_BASE; /* Vector Table Relocation in Internal FLASH. */
}

#define  RCC_CFGR_PLLSRC_HSE                ((uint32_t)0x00010000)        /*!< HSE clock selected as PLL entry clock source */

__attribute__((always_inline)) static inline void StartHSE()
{
    volatile uint32_t StartUpCounter = 0;

    /* SYSCLK, HCLK, PCLK2 and PCLK1 configuration ---------------------------*/
    /* Enable HSE */
    RCC->CR |= ((uint32_t)RCC_CR_HSEON);

    /* Wait till HSE is ready and if Time out is reached exit */
    do
    {
        ++StartUpCounter;
    } while(!(RCC->CR & RCC_CR_HSERDY) && (StartUpCounter < 10000));


    if (RCC->CR & RCC_CR_HSERDY) // HSE started
    {
        /* Enable Prefetch Buffer */
        FLASH->ACR |= FLASH_ACR_PRFTBE;

        /* Flash 2 wait state */
        FLASH->ACR &= (uint32_t)((uint32_t)~FLASH_ACR_LATENCY);
        FLASH->ACR |= (uint32_t)FLASH_ACR_LATENCY_2;

        /* HCLK = SYSCLK */
        RCC->CFGR |= (uint32_t)RCC_CFGR_HPRE_DIV1;

        /* PCLK2 = HCLK */
        RCC->CFGR |= (uint32_t)RCC_CFGR_PPRE2_DIV1;

        /* PCLK1 = HCLK */
        RCC->CFGR |= (uint32_t)RCC_CFGR_PPRE1_DIV2;

        /*  PLL configuration: PLLCLK = HSE * 9 = 72 MHz */
        RCC->CFGR &= (uint32_t)((uint32_t)~(RCC_CFGR_PLLSRC | RCC_CFGR_PLLXTPRE |
                                        RCC_CFGR_PLLMULL));
        RCC->CFGR |= (uint32_t)(RCC_CFGR_PLLSRC_HSE | RCC_CFGR_PLLMULL9);

        /* Enable PLL */
        RCC->CR |= RCC_CR_PLLON;

        /* Wait till PLL is ready */
        StartUpCounter = 0;
        while((RCC->CR & RCC_CR_PLLRDY) == 0 && ++StartUpCounter < 1000){}

        /* Select PLL as system clock source */
        RCC->CFGR &= (uint32_t)((uint32_t)~(RCC_CFGR_SW));
        RCC->CFGR |= (uint32_t)RCC_CFGR_SW_PLL;

        /* Wait till PLL is used as system clock source */
        StartUpCounter = 0;
        while(((RCC->CFGR & (uint32_t)RCC_CFGR_SWS) != (uint32_t)0x08) && ++StartUpCounter < 1000){}
    }
    else // HSE fails to start-up
    {
        ; // add some code here (use HSI)
    }
}

static void hw_setup()
{
    // Enable clocks to the GPIO subsystems (PB for ADC), turn on AFIO clocking to disable SWD/JTAG
    RCC->APB2ENR |= RCC_APB2ENR_IOPAEN | RCC_APB2ENR_IOPBEN | RCC_APB2ENR_IOPCEN | RCC_APB2ENR_AFIOEN;
    // turn off SWJ/JTAG
    //AFIO->MAPR = AFIO_MAPR_SWJ_CFG_DISABLE;
    // turn off USB pullup
    GPIOA->ODR = (1 << 13);
    // Set led (PC13) as opendrain output
    GPIOC->CRH = CRH(13, CNF_ODOUTPUT | MODE_SLOW);
    // Set USB pullup (PA13) as opendrain output
    GPIOA->CRH = CRH(13, CNF_ODOUTPUT | MODE_SLOW);
}



#define IWDG_REFRESH      (uint32_t)(0x0000AAAA)
#define IWDG_WRITE_ACCESS (uint32_t)(0x00005555)
#define IWDG_START        (uint32_t)(0x0000CCCC)

static void iwdg_setup()
{
    uint32_t tmout = 16000000;
    /* Enable the peripheral clock RTC */
    /* (1) Enable the LSI (40kHz) */
    /* (2) Wait while it is not ready */
    RCC->CSR |= RCC_CSR_LSION; /* (1) */
    while((RCC->CSR & RCC_CSR_LSIRDY) != RCC_CSR_LSIRDY)
    {
        if(--tmout == 0) break;   /* (2) */
    }
    /* Configure IWDG */
    /* (1) Activate IWDG (not needed if done in option bytes) */
    /* (2) Enable write access to IWDG registers */
    /* (3) Set prescaler by 64 (1.6ms for each tick) */
    /* (4) Set reload value to have a rollover each 2s */
    /* (5) Check if flags are reset */
    /* (6) Refresh counter */
    IWDG->KR = IWDG_START; /* (1) */
    IWDG->KR = IWDG_WRITE_ACCESS; /* (2) */
    IWDG->PR = IWDG_PR_PR_1; /* (3) */
    IWDG->RLR = 1250; /* (4) */
    tmout = 16000000;
    while(IWDG->SR)
    {
        if(--tmout == 0) break;   /* (5) */
    }
    IWDG->KR = IWDG_REFRESH; /* (6) */
}

static struct NXSendCmd rx_cmd;

// Command received from ISR, processed in main loop
static volatile uint8_t pending_cmd = CMD_None;  // 'R', 'P', or 0 (none)

static void send_ack(void)
{
    static const uint8_t ack[] = { 'd', 'K', '\n', 0x7F };
    HAL_UART_Transmit(&huart1, ack, sizeof(ack), 10);
}

// Start listening for one byte (non-blocking, interrupt-driven)
static void uart_listen(void)
{
    HAL_UART_Receive_IT(&huart1, &rx_cmd.cmd, 1);
    // sizeof(rx_cmd)
}

static uint8_t got_data = 0;

void HAL_UART_RxCpltCallback(UART_HandleTypeDef *huart)
{
    if(huart->Instance != USART1)
        return;

    if(!got_data)
    {
        if(rx_cmd.cmd != CMD_None && rx_cmd.cmd < CMD_END)
        {
            got_data = 1;
            HAL_UART_Receive_IT(&huart1, (uint8_t*)&rx_cmd.data, sizeof(rx_cmd) - 1);
        }
        else
            uart_listen();
    }
    else
    {
        pending_cmd = rx_cmd.cmd;
        got_data = 0;
        uart_listen();
    }
}

static const tusb_rhport_init_t dev_init =
{
    .role = TUSB_ROLE_DEVICE,
    .speed = TUSB_SPEED_FULL
};

// Process pending commands in main loop (debug prints + ACK)
static void uart_poll(void)
{
    uint8_t cmd = pending_cmd;

    if(cmd == CMD_None)
        return;

    pending_cmd = CMD_None;

    switch(cmd)
    {
    case CMD_Reset:
        send_ack();
        debug_println("[CMD] RESET");
        tud_disconnect();
        tusb_deinit(0);
        HAL_Delay(100);
        tusb_init(BOARD_TUD_RHPORT, &dev_init);
        tud_sof_cb_enable(true);
        tud_task();
        IWDG->KR = IWDG_REFRESH; // refresh watch dog
        HAL_Delay(100);
        tud_task();
        IWDG->KR = IWDG_REFRESH; // refresh watch dog
        tud_connect();
        break;

    case CMD_Ping:
        send_ack();
        debug_println("[CMD] PING");
        break;

    case CMD_QueryPlayer:
        debug_println("[CMD] Query Player");
        switch_query_player();
        break;

    case CMD_QueryIMU:
        debug_println("[CMD] Query IMU");
        switch_query_imu();
        break;

    case CMD_ButtonsUpdate:
    case CMD_Tilt:
//        debug_println("[CMD] Update buttons"); // Floods too much@
        switch_receive(&rx_cmd);
        break;

    default:
        debug_println("[CMD] Invalid command!");
        break;
    }
}

int main(void)
{
    uint32_t lastT = 0;

    // Clear memory
    memset(&rx_cmd, 0, sizeof(rx_cmd));
    switch_init_input_state();

    sysreset();
    StartHSE();

    HAL_Init();

    SystemClock_Config();

    hw_setup();

    MX_GPIO_Init();

    USBPU_OFF();

    MX_USART1_UART_Init();

    SysTick_Config(SystemCoreClock / 1000);

    debug_init(&huart1);

    if(RCC->CSR & RCC_CSR_IWDGRSTF)  // watchdog reset occurred
        debug_println("WDGRESET=1");

    if(RCC->CSR & RCC_CSR_SFTRSTF)  // software reset occurred
        debug_println("SOFTRESET=1");

    RCC->CSR |= RCC_CSR_RMVF; // remove reset flags

    debug_println("=== Switch Pro NX-USB boot ===");

    // LED on at boot (PB2, active-low)
    HAL_GPIO_WritePin(LED_GPIO_Port, LED_Pin, GPIO_PIN_RESET);

    USB_init_workaround();
    MX_USB_PCD_Init();

//    tud_disconnect();
//    tusb_deinit(0);
//    HAL_Delay(1000);

    tusb_init(BOARD_TUD_RHPORT, &dev_init);
//    tud_disconnect();
    tud_sof_cb_enable(true);
//    tud_task();
//    HAL_Delay(100);
//    tud_task();
//    HAL_Delay(100);
//    tud_task();
    iwdg_setup();
//    tud_connect();
//    tud_task();
//    USBPU_ON();

    debug_println("USB connected, waiting for host...");

    debug_printf("------------------------------------");
    debug_printf("SYCLK= %dMHz", HAL_RCC_GetSysClockFreq() / 1000000);
    debug_printf("HCLK = %dMHz (%u)", HAL_RCC_GetHCLKFreq() / 1000000, SystemCoreClock);
    debug_printf("APB1 = %dMHz", HAL_RCC_GetPCLK1Freq() / 1000000);
    debug_printf("APB2 = %dMHz", HAL_RCC_GetPCLK2Freq() / 1000000);
    debug_printf("------------------------------------");

    // Start non-blocking UART receive for command protocol
    uart_listen();

    while(1)
    {
        uint32_t t = HAL_GetTick();

        IWDG->KR = IWDG_REFRESH; // refresh watch dog

        if(lastT > t || t - lastT > 499)
        {
            HAL_GPIO_TogglePin(LED_GPIO_Port, LED_Pin);
            lastT = t;
        }

        tud_task();
        // Service any queued protocol responses (handshake, subcommand replies)
        switch_pro_send_queued();

        uart_poll();

        switch_update_state();
    }

    return 0;
}

/**
  * @brief  System Clock Configuration
  *         The system Clock is configured as follow :
  *            System Clock source            = PLL (HSE)
  *            SYSCLK(Hz)                     = 72000000
  *            HCLK(Hz)                       = 72000000
  *            AHB Prescaler                  = 1
  *            APB1 Prescaler                 = 2
  *            APB2 Prescaler                 = 1
  *            PLLMUL                         = 16
  *            Flash Latency(WS)              = 2
  * @param  None
  * @retval None
  */
void SystemClock_Config(void)
{
    RCC_ClkInitTypeDef clkinitstruct = {0};
    RCC_OscInitTypeDef oscinitstruct = {0};
    RCC_PeriphCLKInitTypeDef rccperiphclkinit = {0};

    memset(&clkinitstruct, 0, sizeof(clkinitstruct));
    memset(&oscinitstruct, 0, sizeof(clkinitstruct));
    memset(&rccperiphclkinit, 0, sizeof(rccperiphclkinit));

    /* Enable HSE Oscillator and activate PLL with HSE as source */
    oscinitstruct.OscillatorType  = RCC_OSCILLATORTYPE_HSE;
    oscinitstruct.HSEState        = RCC_HSE_ON;
    oscinitstruct.HSEPredivValue  = RCC_HSE_PREDIV_DIV1;
    oscinitstruct.PLL.PLLMUL      = RCC_PLL_MUL9;
    oscinitstruct.PLL.PLLState    = RCC_PLL_ON;
    oscinitstruct.PLL.PLLSource   = RCC_PLLSOURCE_HSE;

    if(HAL_RCC_OscConfig(&oscinitstruct) != HAL_OK)
    {
        while(1) { ; }
    }

    /* USB clock selection */
    rccperiphclkinit.PeriphClockSelection = RCC_PERIPHCLK_USB;
    rccperiphclkinit.UsbClockSelection = RCC_USBCLKSOURCE_PLL_DIV1_5;
    if(HAL_RCCEx_PeriphCLKConfig(&rccperiphclkinit) != HAL_OK)
    {
        while(1) { ; }
    }

    /* Select PLL as system clock source and configure the HCLK, PCLK1 and PCLK2 clocks dividers */
    clkinitstruct.ClockType = (RCC_CLOCKTYPE_SYSCLK | RCC_CLOCKTYPE_HCLK | RCC_CLOCKTYPE_PCLK1 | RCC_CLOCKTYPE_PCLK2);
    clkinitstruct.SYSCLKSource = RCC_SYSCLKSOURCE_PLLCLK;
    clkinitstruct.AHBCLKDivider = RCC_SYSCLK_DIV1;
    clkinitstruct.APB1CLKDivider = RCC_HCLK_DIV2;
    clkinitstruct.APB2CLKDivider = RCC_HCLK_DIV1;
    if(HAL_RCC_ClockConfig(&clkinitstruct, FLASH_LATENCY_2)!= HAL_OK)
    {
        /* Initialisation Error */
        while(1);
    }
}

void Error_Handler(void)
{
    __disable_irq();
    while(1)
    {}
}
